/*
 * This file was automatically generated by EvoSuite
 * Fri May 05 18:10:51 GMT 2023
 */

package com.example.task_evaluated;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.example.task_evaluated.task_29558;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class task_29558_ESTest extends task_29558_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      task_29558 task_29558_0 = new task_29558();
      // Undeclared exception!
      try { 
        task_29558_0.fetchText("=-Saa[Si", (-1), 3404);
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.task_evaluated.task_29558", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      task_29558 task_29558_0 = new task_29558();
      String string0 = task_29558_0.fetchText("%'", 0, 0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      task_29558 task_29558_0 = new task_29558();
      // Undeclared exception!
      try { 
        task_29558_0.fetchText("", 1, 1);
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.task_evaluated.task_29558", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      task_29558 task_29558_0 = new task_29558();
      // Undeclared exception!
      try { 
        task_29558_0.fetchText("", 2014, 0);
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.task_evaluated.task_29558", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      task_29558 task_29558_0 = new task_29558();
      // Undeclared exception!
      try { 
        task_29558_0.fetchText((String) null, 4062, 4062);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.task_evaluated.task_29558", e);
      }
  }
}
